<?php
include'koneksi.php';
$NAMA_UKM = $_POST['NAMA_UKM'];
$KETUA_UKM = $_POST['KETUA_UKM'];
$WAKIL_UKM = $_POST['WAKIL_UKM '];
$SEKRETARIS1_UKM = $_POST['SEKRETARIS1_UKM'];
$SEKRETARIS2_UKM = $_POST['SEKRETARIS2_UKM'];
$BENDAHARA1_UKM = $_POST['BENDAHARA1_UKM '];
$BENDAHARA2_UKM = $_POST['BENDAHARA2_UKM'];
$VISI_UKM = $_POST['VISI_UKM'];
$MISI_UKM = $_POST['MISI_UKM'];
mysqli_query($koneksi,"insert into user values('','$NAMA_UKM','$KETUA_UKM',
'$WAKIL_UKM','$SEKRETARIS1_UKM','$SEKRETARIS2_UKM','$BENDAHARA1_UKM',
'$BENDAHARA2_UKM','$VISI_UKM','$MISI_UKM')");
header("location:dataukm.php?pesan=input");
?>